/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddTradeRouteImport } from './routes/add-trade'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as JournalRouteImport } from './routes/journal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddTradeRoute = AddTradeRouteImport.update({
  id: '/add-trade',
  path: '/add-trade',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-trade': typeof AddTradeRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/journal': typeof JournalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-trade': typeof AddTradeRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/journal': typeof JournalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-trade': typeof AddTradeRoute
  '/analytics': typeof AnalyticsRoute
  '/history': typeof HistoryRoute
  '/journal': typeof JournalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-trade' | '/analytics' | '/history' | '/journal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-trade' | '/analytics' | '/history' | '/journal'
  id: '__root__' | '/' | '/add-trade' | '/analytics' | '/history' | '/journal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddTradeRoute: typeof AddTradeRoute
  AnalyticsRoute: typeof AnalyticsRoute
  HistoryRoute: typeof HistoryRoute
  JournalRoute: typeof JournalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-trade': {
      id: '/add-trade'
      path: '/add-trade'
      fullPath: '/add-trade'
      preLoaderRoute: typeof AddTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddTradeRoute: AddTradeRoute,
  AnalyticsRoute: AnalyticsRoute,
  HistoryRoute: HistoryRoute,
  JournalRoute: JournalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
